micronaut:
  application:
    name: orderby-error
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**

r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sampledb}
      username: ${DB_USERNAME:postgres}
      password: ${DB_PASSWORD:postgres}
      schema-generate: CREATE_DROP
      dialect: POSTGRES
      options:
        driver: pool
        protocol:
          postgres

logger:
  levels:
    io.micronaut.data.query: DEBUG